[package]
name = "radicle-avatar"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["radicle team <dev@radicle.xyz>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = [ "derive" ] }
